In [1]:
import pandas as pd
import numpy as np

In [2]:
from sklearn.datasets import load_breast_cancer

In [3]:
data = load_breast_cancer()

In [4]:
data.DESCR

'.. _breast_cancer_dataset:\n\nBreast cancer wisconsin (diagnostic) dataset\n--------------------------------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 569\n\n    :Number of Attributes: 30 numeric, predictive attributes and the class\n\n    :Attribute Information:\n        - radius (mean of distances from center to points on the perimeter)\n        - texture (standard deviation of gray-scale values)\n        - perimeter\n        - area\n        - smoothness (local variation in radius lengths)\n        - compactness (perimeter^2 / area - 1.0)\n        - concavity (severity of concave portions of the contour)\n        - concave points (number of concave portions of the contour)\n        - symmetry\n        - fractal dimension ("coastline approximation" - 1)\n\n        The mean, standard error, and "worst" or largest (mean of the three\n        worst/largest values) of these features were computed for each image,\n        resulting in 30 features.  For inst

In [5]:
df = pd.DataFrame(data.data,columns = data.feature_names)

In [6]:
df

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0          17.99         10.38          122.80     1001.0          0.11840   
1          20.57         17.77          132.90     1326.0          0.08474   
2          19.69         21.25          130.00     1203.0          0.10960   
3          11.42         20.38           77.58      386.1          0.14250   
4          20.29         14.34          135.10     1297.0          0.10030   
..           ...           ...             ...        ...              ...   
564        21.56         22.39          142.00     1479.0          0.11100   
565        20.13         28.25          131.20     1261.0          0.09780   
566        16.60         28.08          108.30      858.1          0.08455   
567        20.60         29.33          140.10     1265.0          0.11780   
568         7.76         24.54           47.92      181.0          0.05263   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
0             0.27760         0.30010              0.14710         0.2419   
1             0.07864         0.08690              0.07017         0.1812   
2             0.15990         0.19740              0.12790         0.2069   
3             0.28390         0.24140              0.10520         0.2597   
4             0.13280         0.19800              0.10430         0.1809   
..                ...             ...                  ...            ...   
564           0.11590         0.24390              0.13890         0.1726   
565           0.10340         0.14400              0.09791         0.1752   
566           0.10230         0.09251              0.05302         0.1590   
567           0.27700         0.35140              0.15200         0.2397   
568           0.04362         0.00000              0.00000         0.1587   

     mean fractal dimension  ...  worst radius  worst texture  \
0                   0.07871  ...        25.380          17.33   
1                   0.05667  ...        24.990          23.41   
2                   0.05999  ...        23.570          25.53   
3                   0.09744  ...        14.910          26.50   
4                   0.05883  ...        22.540          16.67   
..                      ...  ...           ...            ...   
564                 0.05623  ...        25.450          26.40   
565                 0.05533  ...        23.690          38.25   
566                 0.05648  ...        18.980          34.12   
567                 0.07016  ...        25.740          39.42   
568                 0.05884  ...         9.456          30.37   

     worst perimeter  worst area  worst smoothness  worst compactness  \
0             184.60      2019.0           0.16220            0.66560   
1             158.80      1956.0           0.12380            0.18660   
2             152.50      1709.0           0.14440            0.42450   
3              98.87       567.7           0.20980            0.86630   
4             152.20      1575.0           0.13740            0.20500   
..               ...         ...               ...                ...   
564           166.10      2027.0           0.14100            0.21130   
565           155.00      1731.0           0.11660            0.19220   
566           126.70      1124.0           0.11390            0.30940   
567           184.60      1821.0           0.16500            0.86810   
568            59.16       268.6           0.08996            0.06444   

     worst concavity  worst concave points  worst symmetry  \
0             0.7119                0.2654          0.4601   
1             0.2416                0.1860          0.2750   
2             0.4504                0.2430          0.3613   
3             0.6869                0.2575          0.6638   
4             0.4000                0.1625          0.2364   
..               ...                   ...             ...   
564           0.4107                0.2216         

In [7]:
target = data.target
target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [8]:
df['target'] = target

In [9]:
df

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0          17.99         10.38          122.80     1001.0          0.11840   
1          20.57         17.77          132.90     1326.0          0.08474   
2          19.69         21.25          130.00     1203.0          0.10960   
3          11.42         20.38           77.58      386.1          0.14250   
4          20.29         14.34          135.10     1297.0          0.10030   
..           ...           ...             ...        ...              ...   
564        21.56         22.39          142.00     1479.0          0.11100   
565        20.13         28.25          131.20     1261.0          0.09780   
566        16.60         28.08          108.30      858.1          0.08455   
567        20.60         29.33          140.10     1265.0          0.11780   
568         7.76         24.54           47.92      181.0          0.05263   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
0             0.27760         0.30010              0.14710         0.2419   
1             0.07864         0.08690              0.07017         0.1812   
2             0.15990         0.19740              0.12790         0.2069   
3             0.28390         0.24140              0.10520         0.2597   
4             0.13280         0.19800              0.10430         0.1809   
..                ...             ...                  ...            ...   
564           0.11590         0.24390              0.13890         0.1726   
565           0.10340         0.14400              0.09791         0.1752   
566           0.10230         0.09251              0.05302         0.1590   
567           0.27700         0.35140              0.15200         0.2397   
568           0.04362         0.00000              0.00000         0.1587   

     mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0                   0.07871  ...          17.33           184.60      2019.0   
1                   0.05667  ...          23.41           158.80      1956.0   
2                   0.05999  ...          25.53           152.50      1709.0   
3                   0.09744  ...          26.50            98.87       567.7   
4                   0.05883  ...          16.67           152.20      1575.0   
..                      ...  ...            ...              ...         ...   
564                 0.05623  ...          26.40           166.10      2027.0   
565                 0.05533  ...          38.25           155.00      1731.0   
566                 0.05648  ...          34.12           126.70      1124.0   
567                 0.07016  ...          39.42           184.60      1821.0   
568                 0.05884  ...          30.37            59.16       268.6   

     worst smoothness  worst compactness  worst concavity  \
0             0.16220            0.66560           0.7119   
1             0.12380            0.18660           0.2416   
2             0.14440            0.42450           0.4504   
3             0.20980            0.86630           0.6869   
4             0.13740            0.20500           0.4000   
..                ...                ...              ...   
564           0.14100            0.21130           0.4107   
565           0.11660            0.19220           0.3215   
566           0.11390            0.30940           0.3403   
567           0.16500            0.86810           0.9387   
568           0.08996            0.06444           0.0000   

     worst concave points  worst symmetry  worst fractal dimension  target  
0                  0.2654          0.4601                  0.11890       0  
1                  0.1860          0.2750                  0.08902       0  
2                  0.2430          0.3613                  0.08758       0  
3                  0.2575          0.6638                  0.17300       0  
4                  0.1625          0.2364                  0.076

In [10]:
df.columns

Index(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error', 'fractal dimension error',
       'worst radius', 'worst texture', 'worst perimeter', 'worst area',
       'worst smoothness', 'worst compactness', 'worst concavity',
       'worst concave points', 'worst symmetry', 'worst fractal dimension',
       'target'],
      dtype='object')

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 31 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   mean radius              569 non-null    float64
 1   mean texture             569 non-null    float64
 2   mean perimeter           569 non-null    float64
 3   mean area                569 non-null    float64
 4   mean smoothness          569 non-null    float64
 5   mean compactness         569 non-null    float64
 6   mean concavity           569 non-null    float64
 7   mean concave points      569 non-null    float64
 8   mean symmetry            569 non-null    float64
 9   mean fractal dimension   569 non-null    float64
 10  radius error             569 non-null    float64
 11  texture error            569 non-null    float64
 12  perimeter error          569 non-null    float64
 13  area error               569 non-null    float64
 14  smoothness error         5

In [12]:
y = df['target'].values
x = df.drop(['target'],axis = 1)

In [13]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [14]:
model = LogisticRegression()

In [15]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.3,random_state = 42)

In [16]:
model.fit(x_train,y_train)

C:\Users\DELL\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [17]:
yp = model.predict(x_test)
yp = yp.reshape(-1,1)
yp.ndim

2

In [18]:
model.predict([[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]])

array([1])

In [19]:
y_test = y_test.reshape(-1,1)

In [20]:
model.score(x_test,y_test)

0.9707602339181286

In [21]:
model.score(x_train,y_train)

0.9371859296482412

In [22]:
from sklearn.metrics import confusion_matrix

In [23]:
confusion_matrix(y_test,yp)

array([[ 59,   4],
       [  1, 107]], dtype=int64)

In [24]:
from sklearn.svm import SVC

In [25]:
model1 = SVC()

In [26]:
model1.fit(x_train,y_train)

SVC()

In [27]:
yp1 = model1.predict(x_test)

In [28]:
model1.score(x_test,y_test)

0.935672514619883

In [29]:
model1.score(x_train,y_train)

0.8994974874371859

In [30]:
confusion_matrix(y_test,yp1)

array([[ 52,  11],
       [  0, 108]], dtype=int64)

In [31]:
from sklearn.neighbors import KNeighborsClassifier

In [32]:
model2 = KNeighborsClassifier()

In [33]:
model2.fit(x_train,y_train)

KNeighborsClassifier()

In [34]:
yp2 = model2.predict(x_test)

In [35]:
model2.score(x_test,y_test)

0.9590643274853801

In [36]:
model2.score(x_train,y_train)

0.9221105527638191

In [37]:
confusion_matrix(y_test,yp2)

array([[ 57,   6],
       [  1, 107]], dtype=int64)

mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error', 'fractal dimension error',
       'worst radius', 'worst texture', 'worst perimeter', 'worst area',
       'worst smoothness', 'worst compactness', 'worst concavity',
       'worst concave points', 'worst symmetry', 'worst fractal dimension

In [38]:
from tkinter import *

In [39]:
def predict():
    radius  = var1.get()
    texture = var2.get()
    perimeter = var3.get()
    area = var4.get()
    smoothness = var5.get()
    compactness = var6.get()
    concavity = var7.get()
    concave = var8.get()
    symmetry = var9.get()
    fractal = var10.get()
    radius_error = var11.get()
    texture_error = var12.get()
    perimeter_error = var13.get()
    area_error = var14.get()
    smootheness_error = var15.get()
    compactness_error = var16.get()
    concavity_error = var17.get()
    concave_error = var18.get()
    symmetry_error = var19.get()
    fractal_error = var20.get()
    worst_radius = var21.get()
    worst_texture = var22.get()
    worst_perimeter = var23.get()
    worst_area = var24.get()
    worst_smootheness = var25.get()
    worst_compactness = var26.get()
    worst_concavity = var27.get()
    worst_concave = var28.get()
    worst_symmetry = var29.get()
    worst_fractal = var30.get()
    
    ypp = model.predict([[radius,texture,perimeter,area,smoothness,compactness,concavity,concave,symmetry,fractal,radius_error,
                         texture_error,perimeter_error,area_error,smootheness_error,compactness_error,concavity_error,concave_error,
                         symmetry_error,fractal_error,worst_radius,worst_texture,worst_perimeter,worst_area,worst_smootheness,worst_compactness,
                         worst_concavity,worst_concave,worst_symmetry,worst_fractal]])

    if ypp == 1:
        ll = Label(root,text = 'person does ',font = 40).place(x = 400,y=300,width = 250)
        lt = Label(root,text = 'not have cancer',font = 40).place(x = 400,y=330,width = 250)
    else:
        lll = Label(root,text = 'person have a cancer',font = 40).place(x = 400,y=300,width = 250)
root = Tk()
root.geometry('700x400')
root.title('Breast cancer finder')



background = PhotoImage(file = r'C:\Users\DELL\Desktop\bluebackground-700x400.png')
bg = Label(root,image = background).place(x = 0,y = 0,width = 700,height = 400)

var1 = IntVar()
l1 = Label(text = 'radius',font = ('helvitica Bold',12),bg = 'royalblue4',fg = 'white').place(x = 0,y=0)
e1 = Entry(root,textvariable = var1).place(x = 140,y = 0,width = 50)

var2 = IntVar()
l2 = Label(text = 'texture',font = ('bold',12),bg = 'royalblue4',fg = 'white').place(x = 0,y=25)
e2 = Entry(root,textvariable = var2).place(x = 140,y = 25,width = 50)

var3 = IntVar()
l3 = Label(text = 'perimeter',font = ('bold',12),bg = 'royalblue4',fg = 'white').place(x = 0,y=50)
e3 = Entry(root,textvariable = var3).place(x = 140,y = 50,width = 50)

var4 = IntVar()
l4 = Label(text = 'area',font = ('bold',12),bg = 'royalblue4',fg = 'white').place(x = 0,y=75)
e4 = Entry(root,textvariable = var4).place(x = 140,y = 75,width = 50)

var5 = IntVar()
l5 = Label(text = 'smoothness',font = ('bold',12),bg = 'royalblue4',fg = 'white').place(x = 0,y=100)
e5 = Entry(root,textvariable = var5).place(x = 140,y = 100,width = 50)


var6 = IntVar()
l6 = Label(text = 'compactness',font = ('bold',12),bg = 'royalblue4',fg = 'white').place(x = 220,y=0)
e6 = Entry(root,textvariable = var6).place(x = 370,y = 0,width = 50)

var7 = IntVar()
l7 = Label(text = 'concavity',font = ('bold',12),bg = 'royalblue4',fg = 'white').place(x = 220,y=25)
e7 = Entry(root,textvariable = var7).place(x = 370,y = 25,width = 50)

var8 = IntVar()
l8 = Label(text = 'concave',font = ('bold',12),bg = 'royalblue4',fg = 'white').place(x = 220,y=50)
e8 = Entry(root,textvariable = var8).place(x = 370,y = 50,width = 50)

var9 = IntVar()
l9 = Label(text = 'symmetry',font = ('bold',12),bg = 'royalblue4',fg = 'white').place(x =220,y=75)
e9 = Entry(root,textvariable = var9).place(x = 370,y = 75,width = 50)

var10 = IntVar()
l10 = Label(text = 'fractal',font = ('bold',12),bg = 'royalblue4',fg = 'white').place(x = 220,y=100)
e10 = Entry(root,textvariable = var10).place(x = 370,y = 100,width = 50)


var11 = IntVar()
l11 = Label(text = 'radius_error',font = ('bold',12),bg = 'royalblue4',fg = 'white').place(x = 450,y=0)
e11= Entry(root,textvariable = var11).place(x = 600,y = 0,width = 50)

var12 = IntVar()
l12= Label(text = 'texture_error',font = ('bold',12),bg = 'royalblue4',fg = 'white').place(x = 450,y=25)
e12 = Entry(root,textvariable = var12).place(x = 600,y = 25,width = 50)

var13 = IntVar()
l13= Label(text = 'perimeter_error',font = ('bold',12),bg = 'royalblue4',fg = 'white').place(x = 450,y=50)
e13= Entry(root,textvariable = var13).place(x = 600,y = 50,width = 50)

var14 = IntVar()
l14= Label(text = 'area_error',font = ('bold',12),bg = 'royalblue4',fg = 'white').place(x =450,y=75)
e14= Entry(root,textvariable = var14).place(x = 600,y = 75,width = 50)

var15 = IntVar()
l15 = Label(text = 'smootheness_error',font = ('bold',12),bg = 'royalblue4',fg = 'white').place(x = 450,y=100)
e15 = Entry(root,textvariable = var15).place(x = 600,y = 100,width = 50)

var16 = IntVar()
l16 = Label(text = 'compactness_error',font = ('bold',12),bg = 'royalblue4',fg = 'white').place(x =0,y=150)
e16= Entry(root,textvariable = var16).place(x = 140,y = 150,width = 50)

var17 = IntVar()
l17= Label(text = 'concavity_error',font = ('bold',12),bg = 'royalblue4',fg = 'white').place(x = 0,y=175)
e17 = Entry(root,textvariable = var17).place(x = 140,y = 175,width = 50)

var18 = IntVar()
l18= Label(text = 'concave_error',font = ('bold',12),bg = 'royalblue4',fg = 'white').place(x = 0,y=200)
e18= Entry(root,textvariable = var18).place(x = 140,y = 200,width = 50)

var19 = IntVar()
l19= Label(text = 'symmetry_error',font = ('bold',12),bg = 'royalblue4',fg = 'white').place(x =0,y=225)
e19= Entry(root,textvariable = var19).place(x = 140,y = 225,width = 50)

var20 = IntVar()
l20 = Label(text = 'fractal_error',font = ('bold',12),bg = 'royalblue4',fg = 'white').place(x = 0,y=250)
e20 = Entry(root,textvariable = var20).place(x = 140,y = 250,width = 50)

var21 = IntVar()
l21 = Label(text = 'worst_radius',font = ('bold',12),bg = 'royalblue4',fg = 'white').place(x = 220,y=150)
e21= Entry(root,textvariable = var21).place(x = 370,y = 150,width = 50)

var22 = IntVar()
l22= Label(text = 'worst_texture',font = ('bold',12),bg = 'royalblue4',fg = 'white').place(x = 220,y=175)
e22 = Entry(root,textvariable = var22).place(x = 370,y = 175,width = 50)

var23 = IntVar()
l23= Label(text = 'worst_perimeter',font = ('bold',12),bg = 'royalblue4',fg = 'white').place(x = 220,y=200)
e23= Entry(root,textvariable = var23).place(x = 370,y = 200,width = 50)

var24 = IntVar()
l24= Label(text = 'worst_area',font = ('bold',12),bg = 'royalblue4',fg = 'white').place(x = 220,y=225)
e24= Entry(root,textvariable = var24).place(x = 370,y = 225,width = 50)

var25 = IntVar()
l25 = Label(text = 'worst_smootheness',font = ('bold',12),bg = 'royalblue4',fg = 'white').place(x = 220,y=250)
e25 = Entry(root,textvariable = var25).place(x = 370,y = 250,width = 50)


var26 = IntVar()
l26 = Label(text = 'worst_compactness',font = ('bold',12),bg = 'royalblue4',fg = 'white').place(x = 450,y=150)
e26= Entry(root,textvariable = var26).place(x = 600,y = 150,width = 50)

var27 = IntVar()
l27= Label(text = 'worst_concavity',font = ('bold',12),bg = 'royalblue4',fg = 'white').place(x = 450,y=175)
e27 = Entry(root,textvariable = var27).place(x = 600,y = 175,width = 50)

var28 = IntVar()
l28= Label(text = 'worst_concave',font = ('bold',12),bg = 'royalblue4',fg = 'white').place(x = 450,y=200)
e28= Entry(root,textvariable = var28).place(x = 600,y = 200,width = 50)

var29 = IntVar()
l29= Label(text = 'worst_symmetry',font = ('bold',12),bg = 'royalblue4',fg = 'white').place(x = 450,y=225)
e29= Entry(root,textvariable = var29).place(x = 600,y = 225,width = 50)

var30 = IntVar()
l30 = Label(text = 'worst_fractal',font = ('bold',12),bg = 'royalblue4',fg = 'white').place(x= 450,y=250)
e30 = Entry(root,textvariable = var30).place(x = 600,y = 250,width = 50)

b1 = Button(root,text = 'predict',command = predict).place(x = 0,y = 300,width = 100)



root.mainloop()